/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author mac
 */
public class modify_student extends javax.swing.JFrame {

    /**
     * Creates new form modify_student
     */
    public modify_student() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        delete_student = new javax.swing.JButton();
        update_student = new javax.swing.JButton();
        stud_id = new javax.swing.JLabel();
        student_id = new javax.swing.JTextField();
        stud_fname = new javax.swing.JLabel();
        stud_lname = new javax.swing.JLabel();
        stud_branch = new javax.swing.JLabel();
        stud_marks = new javax.swing.JLabel();
        stud_mail = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        bname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete_student.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        delete_student.setForeground(new java.awt.Color(51, 51, 255));
        delete_student.setText("DELETE STUDENT");
        delete_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_studentActionPerformed(evt);
            }
        });
        getContentPane().add(delete_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 150, 48));

        update_student.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        update_student.setForeground(new java.awt.Color(0, 51, 255));
        update_student.setText("UPDATE STUDENT");
        update_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_studentActionPerformed(evt);
            }
        });
        getContentPane().add(update_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 157, 48));

        stud_id.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        stud_id.setForeground(new java.awt.Color(255, 255, 255));
        stud_id.setText("ENTER STUDENT ID");
        getContentPane().add(stud_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 170, 33));

        student_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_idActionPerformed(evt);
            }
        });
        getContentPane().add(student_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 170, 30));

        stud_fname.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        stud_fname.setForeground(new java.awt.Color(255, 255, 255));
        stud_fname.setText("FIRST NAME");
        getContentPane().add(stud_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 129, 33));

        stud_lname.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        stud_lname.setForeground(new java.awt.Color(255, 255, 255));
        stud_lname.setText("LAST NAME");
        getContentPane().add(stud_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 129, 33));

        stud_branch.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        stud_branch.setForeground(new java.awt.Color(255, 255, 255));
        stud_branch.setText("BRANCH");
        getContentPane().add(stud_branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 129, 33));

        stud_marks.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        stud_marks.setForeground(new java.awt.Color(255, 255, 255));
        stud_marks.setText("CGPA");
        getContentPane().add(stud_marks, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 129, 33));

        stud_mail.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        stud_mail.setForeground(new java.awt.Color(255, 255, 255));
        stud_mail.setText("MAIL ID");
        getContentPane().add(stud_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 129, 33));
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 150, 30));

        bname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnameActionPerformed(evt);
            }
        });
        getContentPane().add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 150, 30));
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 150, 30));
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 150, 30));
        getContentPane().add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/img/college.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 540, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void student_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_idActionPerformed

    private void bnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnameActionPerformed

    private void delete_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_studentActionPerformed
try
{
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/campus?user=root&password=Cutesss@07");
    Statement st=con.createStatement();
            String q,sid;
            sid=student_id.getText();
            q="delete from student where sid="+sid;
            
            st.executeUpdate(q);
            JOptionPane.showMessageDialog(this, "Student Deleted");
        
}catch(Exception e)
{
     System.out.println(e);
     JOptionPane.showMessageDialog(null,"Connection error");
}
    }//GEN-LAST:event_delete_studentActionPerformed

    private void update_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_studentActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/campus?user=root&password=Cutesss@07");
            Statement st=con.createStatement();
            String q,sid,fn,ln,b,c,em;
            sid=student_id.getText();
            fn=fname.getText();
            ln=lname.getText();
            b=bname.getText();
            c=cname.getText();
            em=mname.getText();
            q="update student set fname='"+fn+"', lname='"+ln+"',branch='"+b+"',marks='"+c+"', mail='"+em+"' where sid="+sid;
            st.executeUpdate(q);
            JOptionPane.showMessageDialog(this, "Student Modified");
        }catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,"Connection error");
        }
    }//GEN-LAST:event_update_studentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modify_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modify_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modify_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modify_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modify_student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bname;
    private javax.swing.JTextField cname;
    private javax.swing.JButton delete_student;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mname;
    private javax.swing.JLabel stud_branch;
    private javax.swing.JLabel stud_fname;
    private javax.swing.JLabel stud_id;
    private javax.swing.JLabel stud_lname;
    private javax.swing.JLabel stud_mail;
    private javax.swing.JLabel stud_marks;
    private javax.swing.JTextField student_id;
    private javax.swing.JButton update_student;
    // End of variables declaration//GEN-END:variables
}
