/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author mac
 */
public class modify_company extends javax.swing.JFrame {

    /**
     * Creates new form modify_company
     */
    public modify_company() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comp_name1 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        del_com = new javax.swing.JButton();
        update_com = new javax.swing.JButton();
        comp_name2 = new javax.swing.JLabel();
        comp_name = new javax.swing.JLabel();
        cgpa = new javax.swing.JTextField();
        seats = new javax.swing.JTextField();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comp_name1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        comp_name1.setForeground(new java.awt.Color(255, 255, 255));
        comp_name1.setText("COMPANY NAME");
        getContentPane().add(comp_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, 40));

        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 210, 40));

        del_com.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        del_com.setForeground(new java.awt.Color(51, 51, 255));
        del_com.setText("DELETE COMPANY");
        del_com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_comActionPerformed(evt);
            }
        });
        getContentPane().add(del_com, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 162, -1));

        update_com.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        update_com.setForeground(new java.awt.Color(0, 51, 255));
        update_com.setText("UPDATE COMPANY");
        update_com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_comActionPerformed(evt);
            }
        });
        getContentPane().add(update_com, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 156, -1));

        comp_name2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        comp_name2.setForeground(new java.awt.Color(255, 255, 255));
        comp_name2.setText("NUMBER OF SEATS");
        getContentPane().add(comp_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, 40));

        comp_name.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        comp_name.setForeground(new java.awt.Color(255, 255, 255));
        comp_name.setText("QUALIFYING CGPA CRITERIA");
        getContentPane().add(comp_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 270, 60));

        cgpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgpaActionPerformed(evt);
            }
        });
        getContentPane().add(cgpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 210, 40));

        seats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsActionPerformed(evt);
            }
        });
        getContentPane().add(seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 210, 40));

        back.setIcon(new javax.swing.ImageIcon("/Users/mac/Desktop/img/college.jpg")); // NOI18N
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 520, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        String n=cname.getText();
        System.out.println(n);
    }//GEN-LAST:event_cnameActionPerformed

    private void cgpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cgpaActionPerformed

    private void seatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsActionPerformed

    private void del_comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_comActionPerformed
        try
        {
         Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost/campus?user=root&password=Cutesss@07");
         Statement st=con.createStatement();
            String q,c;
            c=cname.getText();
            q="delete from company where companyname='"+c+"'";
            
            st.executeUpdate(q);
            JOptionPane.showMessageDialog(this, "Company Deleted");
        
            
        }catch(Exception e)
        {
             System.out.println(e);
            JOptionPane.showMessageDialog(null,"Connection error");
        }
    }//GEN-LAST:event_del_comActionPerformed

    private void update_comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_comActionPerformed
        try
        {
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/campus?user=root&password=Cutesss@07");
            Statement st=con.createStatement();
            String q,cn,nos,cri;
            cn=cname.getText();
            nos=seats.getText();
            cri=cgpa.getText();
            q="update company set num_seats='"+nos+"',cgpa='"+cri+"' where companyname='"+cn+"'";
            st.executeUpdate(q);
            JOptionPane.showMessageDialog(this, "Company Modified");
        }catch(Exception e)
        {
             System.out.println(e);
            JOptionPane.showMessageDialog(null,"Connection error");
        }
    }//GEN-LAST:event_update_comActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modify_company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modify_company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modify_company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modify_company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modify_company().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JTextField cgpa;
    private javax.swing.JTextField cname;
    private javax.swing.JLabel comp_name;
    private javax.swing.JLabel comp_name1;
    private javax.swing.JLabel comp_name2;
    private javax.swing.JButton del_com;
    private javax.swing.JTextField seats;
    private javax.swing.JButton update_com;
    // End of variables declaration//GEN-END:variables
}
